spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astarchia?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # update, validate = 스키마검증
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  ses:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-northeast-2
    from-email: noreply@astarchia.com

logging:
  level:
    org.hibernate.SQL: warn
