spring:
  datasource:
    url: jdbc:mysql://localhost:3306/astarchia?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:tjdals45!}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

aws:
  ses:
    access-key: ${AWS_ACCESS_KEY:}
    secret-key: ${AWS_SECRET_KEY:}
    region: ap-northeast-2
    from-email: noreply@astarchia.com

logging:
  level:
    org.hibernate.SQL: debug